defaults: &defaults
  adapter: postgresql
  pool: 15
  timeout: 5000

development:
  <<: *defaults
  database: aura_qa_development

test:
  <<: *defaults
  database: aura_qa_test

production:
  <<: *defaults
